{
  "module_name": "target_functions",
  "kernel_name": "ScaledUpperTriangMaskedSoftmax",
  "function_name": "ScaledUpperTriangMaskedSoftmax",
  "columns_name": ['mp', 'b', 'h', 'l', 'F_dur(us)', 'B_dur(us)'],
  "targets": [['custom_block_scaled_upper_triang_masked_softmax_cuda_forward'], ['custom_block_scaled_upper_triang_masked_softmax_cuda_backward']],
  "first_n_column": 4, 

  # mp, b, h, l
  "starts":[1, 2, 2, 1024],
  "steps":[2, 2, 2, 64],
  "ends":[1, 8, 64, 2048],
  "operators":['mul', 'mul', 'add', 'add'],
  
  "warmup_shapes":[1, 8, 8, 2048],

  "wait": 4,
  "warmup": 6,

  # must > 5, number of sample for get_profiler and for get_one and get_all to caculate the avrage time cost
  "active": 10,

  # for get_profiler and get_one
  # "shapes":[16, 16, 2048],
  "shapes":[1, 8, 8, 2048],

  # run_function, get_profiler, get_one, get_all
  "run": "get_all"
}

# test command
# python collectorController.py --config_path ./configs/ScaledUpperTriangMaskedSoftmax.yml --precision fp32 --device_num 0
# python sampling_controller.py --config_path ./configs/test/ScaledUpperTriangMaskedSoftmax.yml --precision fp16 